apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: customdemo
  title: custom demo
  description: An template for the scaffolder that creates a Django service
  tags:
    - django
spec:
  owner: himanshu.mishra@harness.io
  type: service
  parameters:
    - title: Django Service Details
      required:
        - name
        - repository
        - isPublish
        - uitoken
      properties:
        name:
          title: Name of your Django Service
          type: string
          description: Unique name of the service
        repository:
          title: Name of the Repository
          type: string
          description: This will be the name of Repository on Github
        isPublish:
          title: Do you wish to publish the internal registry?
          type: boolean
        uitoken:
          title: Name
          type: string
          description: My custom name for the component
          ui:field: ValidateKebabCase
